version: "3.8"
services:
    app:
        container_name: app-buuGym
        build:
            context: ./docker/laravel
            dockerfile: Dockerfile
        working_dir: /var/www/code
        volumes:
            - .:/var/www/code
        networks:
            - buuGym-network

    web:
        container_name: web-buuGym
        image: nginx
        working_dir: /var/www/code
        user: root
        volumes:
            - .:/var/www/code
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - buuGym-network
    node:
        image: node:16
        tty: true
        working_dir: /var/www/code
        volumes:
            - .:/var/www/code
    database:
        container_name: mysql-buuGym
        build: ./docker/mysql/database
        volumes:
            - buuGym-database:/var/lib/mysql
            - ./docker/mysql/database:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: buuGym
            MYSQL_USER: buuGym
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - 3307:3306
        networks:
            - buuGym-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - "8081:80"
        environment:
            PMA_HOSTS: database
            PMA_PORT: 3307
            PMA_USER: buuGym
            PMA_PASSWORD : 123456
        networks:
            - buuGym-network

    minio:
        image: minio/minio:latest
        container_name: minio-buuGym
        volumes:
            - minio-store:/data
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ":9001"
        networks:
            - buuGym-network

networks:
    buuGym-network:
        driver: bridge

volumes:
    buuGym-database:
    minio-store:
